### PR TITLE
Don't use the root named route. Future Rails versions don't let you h…

### PR DESCRIPTION
**Pull request by josephsofaer**
…ave named route collisions.

@nelgau this should keep the same route but not take the `root` name

### CODE REVIEW

**Comment by BMorearty** [comment]
Wow, this might fix a longstanding issue: `root_path` sometimes takes you to the trebuchet root instead of the main app root.

**Comment by josephsofaer** [comment]
lolololol really?

**Comment by josephsofaer** [comment]
Well, actually I know that app.root_url will give you /trebuchet once I found this so that doesn't surprise me. I think it's funny someone else saw this PR and also saw this behavior.

**Comment by josephsofaer** [comment]
@BMorearty We have three `root` routes in Monorail too btw

**Comment by nelgau** [comment]
:+1:

**Comment by josephsofaer** [comment]
In Monorail:

before:
```
irb(main):001:0> app.root_path
=> "/trebuchet"
```

after:
```
irb(main):002:0> app.root_path
=> "/"
```

**Pull request merged**
